### ISSUE TITLE
CRS issue in organizeBirds(x=data, grid=grid)

### ISSUE THREAD

**Issue by antpn** [Greensway/BIRDS#9]
**Decription**
When a grid is added to `organizeBirds(x=data, grid=grid)` it results in an error "identicalCRS(x, y) is not TRUE". 
The error comes from the function `getGridIDs` (line 139) in organizeBIRDS. In `sp::over()` the inputs don't have the same CRS, even thou they should have. 

**To Reproduce**
```
grid <- rgdal::readOGR(dsn="path/to/.shp")
grid <- sp::spTransform(grid, CRSobj = CRS("+init=epsg:4326"))
ob <- BIRDS::organizeBirds(x = BIRDS::bombusObs, dataCRS = "+init=epsg:4326", grid = grid)
```
**Expected behavior**
There shouldn’t be an error.

**Comment by rsbivand** [comment]
In reverse dependency checks, there appear to be more problems with current **sp** from github - rsbivand/sp and R-Forge **rgdal**.  The underlying problem seems to stem from CRS(proj4string(x)), testing that proj4string() values are equal, and so on. Be aware that proj4string() values are retained only for out-of-date PROJ/GDAL versions, and that other mechanisms are used replacing the use of Proj4 strings with WKT2_2019 strings for PROJ >= 6 and GDAL >= 3 (already in the CRAN Windows binaries of sf and rgdal). You also use constructions like `points@proj4string` which should always be slot(points, "proj4string"). This is certainly not resolved. There are multiple errors when running soon to be released sp/rgdal with current PROJ/GDAL both on released BIRDS, and possibly more problems with BIRDS master.

**Comment by aleruete** [comment]
thank you @rsbivand I will add this as a new issue to check compatibility with thte new RGDAL and sp
